### ISSUE TITLE
Angularjs Image not loading

### ISSUE THREAD

**Issue by waltercolindres** [Treri/me-lazyload#1]
Using AngularJS v1.3.8

Images not loading. Tried a static url and a dynamic version.

**Comment by ik0r** [comment]
@waltercolindres could you please give me a demo?

**Comment by ychow** [comment]
it's not working

**Comment by primaryobjects** [comment]
The instructions forget to mention, you have to add the 'me-lazyload' clause to your angular.module() line:

``` javascript
var app = angular.module('myApp', ['me-lazyload']);
```

By the way, it would be nice if there was a method for revalidating. For example, inside an ng-repeat if you sort or filter the results, the images do not update until you actually scroll. :(

**Comment by ik0r** [comment]
Thanks, I will update the README.
And I will check, if I can add one revalidating method.
