### ISSUE TITLE
Lazy loading is not working with md-content in angular-material.

### ISSUE THREAD

**Issue by amanguptadev** [Treri/me-lazyload#10]
Images do not load on scrolling the md-content area, but it does load when I resize the window.

If you have ever used it with md-content  then please suggest me how to do that.

**Comment by amanguptadev** [comment]
It is working now.

your me-lazyimg directive is working perfectly. I've just add the lazy-container to my md-content and it is now working like a charm.
https://github.com/treri/me-lazyimg

Thank you.

**Comment by ik0r** [comment]
@amanguptadev Thanks for your like :-)

issue closed
