### ISSUE TITLE
Keeps on firing image loading requests even after I have navigated to another page.

### ISSUE THREAD

**Issue by ketansp** [Treri/me-lazyload#3]
I am using this library in my application and its being used on many pages. For the sake of explanation, lets consider this example. Suppose I have n number of lazy-src tags on my home page. When I scroll, images load properly. No issues with that. Now, I go to another page where I am not using these tags, the library still keeps on loading images from previous home page, even when I scroll down this new page. This issue got highlighted only after having an error from image http request. Like 404 or 403 or so.  Otherwise, one would not even realize about this issue.

**Comment by ik0r** [comment]
what's the expected result?

**Comment by ketansp** [comment]
As per my understanding, when user navigates from page where there are lazy loading images, to any other page in the same application, the library should stop checking for lazy-src directives in the previous page and should stop firing requests for loading images, in the background.

**Comment by ik0r** [comment]
When navigate to another page, are these img tags destroied or removed?
If these tags are still in DOM tree, I think maybe these loading are done by browser?

**Comment by ik0r** [comment]
Now all images are loaded by browser itself, I don't use `new Image()` or something like to loading image. The problem is we don't have an chance to stop browser loading image

**Comment by mytholog** [comment]
My patch should fix this issue

**Comment by Treri** [comment]
@mytholog I saw your code.
But you cleared the global-like `elements` in local $scope destroy event. When elements are cleared, all other lazy-loading are cleared also, but this is not expected.

The `$destroy` event may also be fired when not navigating another page, like change tabs content, or delete some images.

**Comment by ik0r** [comment]
@mytholog  I saw your code.
But you cleared the global-like elements in local $scope destroy event. When elements are cleared, all other lazy-loading are cleared also, but this is not expected.

The $destroy event may also be fired when not navigating another page, like change tabs content, or delete some images.

**Comment by ik0r** [comment]
@ketansp I added code to delete iElement and scope reference from `elements` when a lazySrc element destroy.

I think may the problem can be solved.

**Comment by ketansp** [comment]
I tetsted @mytholog 's patch. It works.

**Comment by ketansp** [comment]
Negative! @Treri tested this issue with your latest commit and it persists.

**Comment by ik0r** [comment]
@ketansp Maybe I missed something. But @mytholog 's code also have problems.

Could you please give me a demo or test page? I will see this problem more

**Comment by ketansp** [comment]
I have put up a fiddle here. http://jsfiddle.net/ketansp/09hxou2a/1/ View students is the page where I have lazy loaded images. Only two images have a valid path. Others would give you a 404. Keep your browser console open. Now, go to view students page, then to add students. Scroll on add students page. Observe browser console for error messages.

**Comment by ik0r** [comment]
@ketansp Thanks, let me have a look

**Comment by ketansp** [comment]
Note- This issue persists for images without error as well.

**Comment by ik0r** [comment]
@ketansp Did you see my latest commit? I saw your jsfiddle, but your commit id is old. You didn't include my new commit.
My latest commit id is 7bf918b624a2feeaf57755c209597279f4063cb8
you jsfiddle commit id is 9aefcacf4df663b04ba838ccdceebfc7a72b215a, 9aefcacf4df663b04ba838ccdceebfc7a72b215a is my last commit (Commits on Apr 18, 2015)

**Comment by ketansp** [comment]
My apologies. I must have missed this. Yes, your solution works. Thanks. Closing this issue.
